#!/usr/bin/env bash
# Zeus Scanner — one-line installer for Termux (also works on plain Linux).
#   curl -fsSL https://raw.githubusercontent.com/frankfuvgfugkfc/scanner/main/install.sh | bash
set -euo pipefail

REPO="${ZEUS_REPO:-frankfuvgfugkfc/scanner}"
BRANCH="${ZEUS_BRANCH:-main}"
RAW="${ZEUS_RAW_BASE:-https://raw.githubusercontent.com/$REPO/$BRANCH}"
XRAY_TAG="${ZEUS_XRAY_TAG:-latest}"
PORT="${ZEUS_PORT:-8000}"

if [ -n "${PREFIX:-}" ] && [ -d "${PREFIX:-}/bin" ]; then
    TERMUX=1
    HOME_DIR="${HOME:-/data/data/com.termux/files/home}"
    BIN_DIR="$PREFIX/bin"
else
    TERMUX=0
    HOME_DIR="${HOME:-$PWD}"
    BIN_DIR="$HOME_DIR/.local/bin"
fi
DEST="${ZEUS_DIR:-$HOME_DIR/zeus-scanner}"

R=$'\033[91m'; G=$'\033[92m'; Y=$'\033[93m'; C=$'\033[96m'; D=$'\033[90m'; N=$'\033[0m'
say()  { printf '%s\n' "${C}::${N} $*"; }
ok()   { printf '%s\n' "${G} ✓${N} $*"; }
warn() { printf '%s\n' "${Y} !${N} $*"; }
die()  { printf '%s\n' "${R} ✗${N} $*" >&2; exit 1; }

printf '%s\n' "$C=============================================$N"
printf '%s\n' "$G           ZEUS SCANNER — installer$N"
printf '%s\n' "$D    clean Cloudflare IP finder + Xray core$N"
printf '%s\n' "$C=============================================$N"

# ---------------------------------------------------------------- dependencies
say "checking dependencies"
NEED=""
for tool in curl unzip python3; do
    command -v "$tool" >/dev/null 2>&1 || NEED="$NEED $tool"
done
# Termux ships python3 as the "python" package.
if [ -n "$NEED" ]; then
    NEED="${NEED// python3/ python}"
    if [ "$TERMUX" = 1 ]; then
        say "installing:$NEED"
        # shellcheck disable=SC2086  # word-splitting on $NEED is intentional (multiple packages)
        pkg install -y $NEED >/dev/null 2>&1 || pkg install -y $NEED || die "pkg install failed"
    elif command -v apt-get >/dev/null 2>&1; then
        say "installing:$NEED (sudo apt-get)"
        # shellcheck disable=SC2086
        sudo apt-get update -qq && sudo apt-get install -y $NEED || die "apt-get install failed"
    else
        die "missing tools:$NEED — install them and re-run"
    fi
fi

command -v python3 >/dev/null 2>&1 || die "python3 still not on PATH"
ok "$(python3 --version)"

# ------------------------------------------------------------------- xray core
# Termux runs on Android, so the android builds are the ones with the right libc.
case "$(uname -m)" in
    aarch64|arm64)  [ "$TERMUX" = 1 ] && ZIP="Xray-android-arm64-v8a.zip" || ZIP="Xray-linux-arm64-v8a.zip" ;;
    armv7l|armv8l)  ZIP="Xray-linux-arm32-v7a.zip" ;;
    x86_64|amd64)   [ "$TERMUX" = 1 ] && ZIP="Xray-android-amd64.zip"     || ZIP="Xray-linux-64.zip" ;;
    i686|i386)      ZIP="Xray-linux-32.zip" ;;
    *)              die "unsupported CPU: $(uname -m)" ;;
esac

if [ "$XRAY_TAG" = latest ]; then
    XRAY_URL="https://github.com/XTLS/Xray-core/releases/latest/download/$ZIP"
else
    XRAY_URL="https://github.com/XTLS/Xray-core/releases/download/$XRAY_TAG/$ZIP"
fi

mkdir -p "$DEST/bin"
cd "$DEST"

say "downloading Xray core ($ZIP)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
curl -fL# --retry 3 --retry-delay 2 -o "$TMP/xray.zip" "$XRAY_URL" \
    || die "could not download Xray from $XRAY_URL"
unzip -oq "$TMP/xray.zip" -d "$TMP/x" || die "Xray archive is corrupt"
[ -f "$TMP/x/xray" ] || die "no xray binary inside the archive"
install -m 755 "$TMP/x/xray" "$DEST/bin/xray" 2>/dev/null \
    || { cp -f "$TMP/x/xray" "$DEST/bin/xray" && chmod 755 "$DEST/bin/xray"; }
for extra in geoip.dat geosite.dat; do
    [ -f "$TMP/x/$extra" ] && cp -f "$TMP/x/$extra" "$DEST/bin/$extra"
done
ok "$("$DEST/bin/xray" version | head -n1)"

# --------------------------------------------------------------- scanner files
say "downloading scanner files"
for f in index.html tailwind.css server.py xray.py; do
    curl -fsSL --retry 3 --retry-delay 2 -o "$DEST/$f.part" "$RAW/$f" \
        || die "could not download $f from $RAW/$f"
    [ -s "$DEST/$f.part" ] || die "$f came back empty"
    mv -f "$DEST/$f.part" "$DEST/$f"
    printf '%s\n' "$D   $f$N"
done
python3 -c "import ast,sys; [ast.parse(open(f,encoding='utf-8').read(),f) for f in sys.argv[1:]]" \
    "$DEST/server.py" "$DEST/xray.py" || die "downloaded python files are broken"
ok "scanner files in place"

# -------------------------------------------------------------------- launcher
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/zeus" <<LAUNCHER
#!/usr/bin/env bash
# Zeus Scanner launcher — generated by install.sh
set -euo pipefail
DEST="$DEST"
export XRAY_BIN="\${XRAY_BIN:-\$DEST/bin/xray}"
export XRAY_LOCATION_ASSET="\${XRAY_LOCATION_ASSET:-\$DEST/bin}"
export ZEUS_PORT="\${ZEUS_PORT:-$PORT}"
cd "\$DEST"
URL="http://127.0.0.1:\$ZEUS_PORT/"
# Termux can hand the URL to the real Android browser; ignore it if unavailable.
if command -v termux-open-url >/dev/null 2>&1; then
    ( sleep 2; termux-open-url "\$URL" >/dev/null 2>&1 || true ) &
fi
exec python3 server.py
LAUNCHER
chmod 755 "$BIN_DIR/zeus"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not on PATH — run it as $BIN_DIR/zeus" ;;
esac

printf '%s\n' "$C=============================================$N"
ok "installed in $DEST"
printf '%s\n' ""
printf '%s\n' "  ${G}zeus${N}          ${D}start the scanner${N}"
printf '%s\n' "  ${D}then open${N}   ${Y}http://127.0.0.1:$PORT/${N}"
printf '%s\n' ""
printf '%s\n' "$D  update:  curl -fsSL $RAW/install.sh | bash$N"
printf '%s\n' "$C=============================================$N"
